FROM maven AS build
WORKDIR /usr/metadata

# build maven .m2 cache as layer for reuse
COPY pom.xml /usr/metadata/
RUN mvn dependency:go-offline -B

# build application as fat executable JAR
COPY src /usr/metadata/src
RUN mvn package -DskipTests


FROM openjdk:alpine
COPY --from=build /usr/metadata/target/metadata-service.jar metadata-service.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","-Xms256m", "-Xmx512m","/metadata-service.jar"]